sudo: required
dist: trusty
language: java

jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - sudo apt-get install eclipse
install: cd com.hribol.bromium.dsl.parent && mvn clean install && cd .. && mvn clean install coveralls:report