sudo: required
dist: trusty
language: java

jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - "Xvfb :1 -screen 0 1360x1024x24 &"
  - "export DISPLAY=:1"
install: cd com.hribol.bromium.dsl.parent && mvn clean install && cd .. && mvn clean install coveralls:report