sudo: required
dist: trusty
language: java
env: DISPLAY=':99.0'

jdk:
  - oraclejdk8

before_script:
  - sh -e /etc/init.d/xvfb start

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install: mvn clean install coveralls:report